version: '2'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest-4x
    build: otrs
    ports:
    - "80:80"
  # If running behind a proxy container, expose the ports instead
  # and link the proxy container to this one.
  #  expose:
  #  - "80"
    links:
    - mariadb:mariadb
    - postfix:postfix
    env_file: ../docker-otrs/otrs-setup.env
    volumes_from:
    - data-otrs
  # If you want to run the installer, uncomment this:
  #   environment:
  #       OTRS_INSTALL: "yes"
  # If you want to restore a backup, uncomment this:
    environment:
  #       OTRS_INSTALL: "restore"
  #       OTRS_BACKUP_DATE: "2015-06-02_06-22"
  # To change email time fetching set OTRS_POSTMASTER_FETCH_TIME (set it to 0 to disable email fetching):
        OTRS_POSTMASTER_FETCH_TIME: 0
        OTRS_DEBUG: "yes"
  # To set the default skin:
  #      OTRS_AGENT_SKIN: "ivory"
  #      OTRS_DROP_DATABASE: "yes"
  #      OTRS_TICKET_COUNTER: 500
  #      OTRS_NUMBER_GENERATOR: "AutoIncrement"
  #      OTRS_LANGUAGE: "es"

  mariadb:
    build: mariadb
    expose:
    - "3306"
    volumes_from:
      - data
    environment:
        MYSQL_ROOT_PASSWORD: changeme
  postfix:
     image: juanluisbaptiste/postfix:latest
     expose:
     - "25"
     env_file: ../../credentials-smtp.env
  data:
    image: centos/mariadb:latest
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true
  data-otrs:
    image: juanluisbaptiste/otrs:latest-4x
    volumes:
    - ./volumes/config:/opt/otrs/Kernel
    - ./volumes/backup:/var/otrs/backups
    - "/etc/localtime:/etc/localtime:ro"

    command: /bin/true
