otrs:
  #image: juanluisbaptiste/otrs:4.0.17-otrs-4_0_x-289505a7
  image: registry.ctecsas.com/ctecsas/otrs:latest
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose:
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  env_file: otrs-setup.env
  volumes_from:
  - data-otrs
# If you want to run the installer, uncomment this:
#   environment:
#       OTRS_INSTALL: "yes"
mariadb:
  image: juanluisbaptiste/otrs-mariadb:latest
  expose:
  - "3306"
  volumes_from:
    - data
  environment:
      MYSQL_ROOT_PASSWORD: changeme
postfix:
   image: juanluisbaptiste/postfix:latest
   expose:
   - "25"
   env_file: ../../credentials-smtp.env
data:
  image: centos/mariadb:latest
  volumes:
  - "/home/juancho/git/docker/docker-otrs-4x/volumes/mysql:/var/lib/mysql"
  #- /var/lib/mysql
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
data-otrs:
  image: juanluisbaptiste/otrs:4.0.17-otrs-4_0_x-289505a7
  volumes:
  #- ./config:/config
  - ./volumes/config:/opt/otrs/Kernel
  - "./otrs/backup:/var/otrs/backups"
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
