otrs:
  image: juanluisbaptiste/otrs:latest-4x
  ports:
  - "80:80"
# If running behind a proxy container, expose the ports instead
# and link the proxy container to this one.
#  expose:
#  - "80"
  links:
  - mariadb:mariadb
  - postfix:postfix
  env_file: otrs-setup.env
  volumes_from:
  - data-otrs
# If you want to run the installer, uncomment this:
#   environment:
#       OTRS_INSTALL: "yes"
mariadb:
  image: juanluisbaptiste/otrs-mariadb:latest
  expose:
  - "3306"
  volumes_from:
    - data
  environment:
      MYSQL_ROOT_PASSWORD: changeme
postfix:
   image: juanluisbaptiste/postfix:latest
   expose:
   - "25"
   env_file: ../../credentials-smtp.env
data:
  image: centos/mariadb:latest
  volumes:
  - ./volumes/mysql:/var/lib/mysql
    #- /var/lib/mysql
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
data-otrs:
  image: juanluisbaptiste/otrs:latest-4x
  volumes:
  - ./volumes/config:/opt/otrs/Kernel
#  - /opt/otrs/Kernel
  - "./volumes/backup:/var/otrs/backups"
  - "/etc/localtime:/etc/localtime:ro"
  command: /bin/true
